spring:
  application:
    name: starlog_BE
  datasource:
    url: ${DATA_SOURCE_URL}
    username: ${DATA_SOURCE_USERNAME}
    password: ${DATA_SOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

fortune:
  prompt: ${FORTUNE_PROMPT}
  api-key: ${GEMINI_API_KEY}
  model: ${GEMINI_MODEL}